import { prisma } from "@/lib/prisma";

export const DEFAULT_SETTINGS = {
  AUTO_POSTING_ENABLED: process.env.AUTO_POSTING_ENABLED ?? "true",
  DEFAULT_POST_TIMES: process.env.DEFAULT_POST_TIMES ?? "08:00,12:30,20:00",
  API_MONTHLY_LIMIT: process.env.API_MONTHLY_LIMIT ?? "10000",
  API_WARNING_THRESHOLD: process.env.API_WARNING_THRESHOLD ?? "0.8",
  BLOCK_AFFILIATE_DIRECT_LINKS:
    process.env.BLOCK_AFFILIATE_DIRECT_LINKS ?? "true",
  ALLOWED_LINK_DOMAINS:
    process.env.ALLOWED_LINK_DOMAINS ??
    "example.com,note.com,blogspot.com,instagram.com,pinterest.com,youtube.com",
  BLOCKED_LINK_DOMAINS:
    process.env.BLOCKED_LINK_DOMAINS ??
    "px.a8.net,a8.net,afi-b.com,t.afi-b.com,accesstrade.net,valuecommerce.com,ck.jp.ap.valuecommerce.com,bit.ly,tinyurl.com,x.gd,is.gd,00m.in",
  WORDPRESS_MOCK_MODE: process.env.WORDPRESS_MOCK_MODE ?? "true",
  WORDPRESS_DEFAULT_STATUS: process.env.WORDPRESS_DEFAULT_STATUS ?? "draft",
  WORDPRESS_REQUEST_TIMEOUT_MS:
    process.env.WORDPRESS_REQUEST_TIMEOUT_MS ?? "15000",
  WORDPRESS_ALLOWED_STATUSES:
    process.env.WORDPRESS_ALLOWED_STATUSES ?? "draft,pending,private,publish",
  WORDPRESS_DEFAULT_AUTHOR: process.env.WORDPRESS_DEFAULT_AUTHOR ?? "",
  WORDPRESS_ALLOW_PUBLISH: process.env.WORDPRESS_ALLOW_PUBLISH ?? "false",
  WORDPRESS_REQUIRE_CONFIRM_FOR_PUBLISH:
    process.env.WORDPRESS_REQUIRE_CONFIRM_FOR_PUBLISH ?? "true",
  WORDPRESS_REQUIRE_CONFIRM_FOR_PUBLISHED_UPDATE:
    process.env.WORDPRESS_REQUIRE_CONFIRM_FOR_PUBLISHED_UPDATE ?? "true",
  WORDPRESS_AUTO_ADD_ALLOWED_DOMAIN:
    process.env.WORDPRESS_AUTO_ADD_ALLOWED_DOMAIN ?? "true",
  CANVA_MOCK_MODE: process.env.CANVA_MOCK_MODE ?? "true",
  CANVA_REQUEST_TIMEOUT_MS: process.env.CANVA_REQUEST_TIMEOUT_MS ?? "20000",
  CANVA_DEFAULT_EXPORT_FORMAT: process.env.CANVA_DEFAULT_EXPORT_FORMAT ?? "png",
  CANVA_USE_AUTOFILL: process.env.CANVA_USE_AUTOFILL ?? "true",
  IMAGE_STORAGE_MODE: process.env.IMAGE_STORAGE_MODE ?? "local",
  IMAGE_STORAGE_DIR:
    process.env.IMAGE_STORAGE_DIR ?? "./public/generated-images",
  IMAGE_PUBLIC_BASE_URL:
    process.env.IMAGE_PUBLIC_BASE_URL ?? "/generated-images",
  IMAGE_MOCK_MODE: process.env.IMAGE_MOCK_MODE ?? "true",
  IMAGE_MAX_FILE_SIZE_MB: process.env.IMAGE_MAX_FILE_SIZE_MB ?? "10",
  WORDPRESS_ENABLE_MEDIA_UPLOAD:
    process.env.WORDPRESS_ENABLE_MEDIA_UPLOAD ?? "false",
  WORDPRESS_MEDIA_MOCK_MODE: process.env.WORDPRESS_MEDIA_MOCK_MODE ?? "true",
  WORDPRESS_FEATURED_MEDIA_UPDATE_ENABLED:
    process.env.WORDPRESS_FEATURED_MEDIA_UPDATE_ENABLED ?? "false",
  X_MEDIA_UPLOAD_ENABLED: process.env.X_MEDIA_UPLOAD_ENABLED ?? "false",
  X_MEDIA_MOCK_MODE: process.env.X_MEDIA_MOCK_MODE ?? "true",
  X_MEDIA_MAX_FILE_SIZE_MB: process.env.X_MEDIA_MAX_FILE_SIZE_MB ?? "5",
  AFFILIATE_MOCK_MODE: process.env.AFFILIATE_MOCK_MODE ?? "true",
  AFFILIATE_CSV_IMPORT_ENABLED:
    process.env.AFFILIATE_CSV_IMPORT_ENABLED ?? "true",
  AFFILIATE_SCRAPING_ENABLED: process.env.AFFILIATE_SCRAPING_ENABLED ?? "false",
  AFFILIATE_DIRECT_X_LINK_BLOCK:
    process.env.AFFILIATE_DIRECT_X_LINK_BLOCK ?? "true",
  AFFILIATE_MASK_LINKS_IN_UI: process.env.AFFILIATE_MASK_LINKS_IN_UI ?? "true",
  GROWTH_SCORE_ENABLED: process.env.GROWTH_SCORE_ENABLED ?? "true",
  GROWTH_SCORE_DEFAULT_PERIOD_DAYS:
    process.env.GROWTH_SCORE_DEFAULT_PERIOD_DAYS ?? "30",
  GROWTH_SCORE_MIN_DATA_DAYS: process.env.GROWTH_SCORE_MIN_DATA_DAYS ?? "7",
  GROWTH_SCORE_REQUIRE_HUMAN_REVIEW:
    process.env.GROWTH_SCORE_REQUIRE_HUMAN_REVIEW ?? "true",
  REVENUE_DEFAULT_CURRENCY: process.env.REVENUE_DEFAULT_CURRENCY ?? "JPY",
  REVENUE_ESTIMATION_MODE: process.env.REVENUE_ESTIMATION_MODE ?? "manual",
  REVENUE_HASH_ORDER_IDS: process.env.REVENUE_HASH_ORDER_IDS ?? "true",
  GA4_MOCK_MODE: process.env.GA4_MOCK_MODE ?? "true",
  GA4_API_ENABLED: process.env.GA4_API_ENABLED ?? "false",
  GOOGLE_SEARCH_CONSOLE_MOCK_MODE:
    process.env.GOOGLE_SEARCH_CONSOLE_MOCK_MODE ?? "true",
  GOOGLE_SEARCH_CONSOLE_API_ENABLED:
    process.env.GOOGLE_SEARCH_CONSOLE_API_ENABLED ?? "false",
  GA4_CSV_IMPORT_ENABLED: process.env.GA4_CSV_IMPORT_ENABLED ?? "true",
  GA4_REQUEST_TIMEOUT_MS: process.env.GA4_REQUEST_TIMEOUT_MS ?? "20000",
  GOOGLE_SEARCH_CONSOLE_CSV_IMPORT_ENABLED:
    process.env.GOOGLE_SEARCH_CONSOLE_CSV_IMPORT_ENABLED ?? "true",
  GOOGLE_SEARCH_CONSOLE_REQUEST_TIMEOUT_MS:
    process.env.GOOGLE_SEARCH_CONSOLE_REQUEST_TIMEOUT_MS ?? "20000",
  SEO_ANALYSIS_ENABLED: process.env.SEO_ANALYSIS_ENABLED ?? "true",
  SEO_DEFAULT_PERIOD_DAYS: process.env.SEO_DEFAULT_PERIOD_DAYS ?? "28",
  SEO_MIN_DATA_DAYS: process.env.SEO_MIN_DATA_DAYS ?? "7",
  SEO_IMPROVEMENT_MOCK_MODE: process.env.SEO_IMPROVEMENT_MOCK_MODE ?? "true",
  SEO_REQUIRE_HUMAN_REVIEW: process.env.SEO_REQUIRE_HUMAN_REVIEW ?? "true",
  SEO_CSV_IMPORT_ENABLED: process.env.SEO_CSV_IMPORT_ENABLED ?? "true",
  SEO_POSITION_WARNING_THRESHOLD:
    process.env.SEO_POSITION_WARNING_THRESHOLD ?? "20",
  SEO_CTR_LOW_THRESHOLD: process.env.SEO_CTR_LOW_THRESHOLD ?? "0.02",
  SEO_HIGH_IMPRESSION_THRESHOLD:
    process.env.SEO_HIGH_IMPRESSION_THRESHOLD ?? "1000",
  GOOGLE_API_REAL_CONNECTION_ENABLED:
    process.env.GOOGLE_API_REAL_CONNECTION_ENABLED ?? "false",
  GOOGLE_OAUTH_SCOPES:
    process.env.GOOGLE_OAUTH_SCOPES ??
    "https://www.googleapis.com/auth/analytics.readonly https://www.googleapis.com/auth/webmasters.readonly",
  GA4_SYNC_ENABLED: process.env.GA4_SYNC_ENABLED ?? "false",
  GA4_DEFAULT_SYNC_DAYS: process.env.GA4_DEFAULT_SYNC_DAYS ?? "28",
  GA4_MAX_SYNC_DAYS: process.env.GA4_MAX_SYNC_DAYS ?? "90",
  GA4_MAX_ROWS_PER_REQUEST: process.env.GA4_MAX_ROWS_PER_REQUEST ?? "10000",
  GA4_ABSOLUTE_MAX_ROWS_PER_REQUEST:
    process.env.GA4_ABSOLUTE_MAX_ROWS_PER_REQUEST ?? "250000",
  GA4_RETURN_PROPERTY_QUOTA: process.env.GA4_RETURN_PROPERTY_QUOTA ?? "true",
  GOOGLE_SEARCH_CONSOLE_SYNC_ENABLED:
    process.env.GOOGLE_SEARCH_CONSOLE_SYNC_ENABLED ?? "false",
  GOOGLE_SEARCH_CONSOLE_DEFAULT_SYNC_DAYS:
    process.env.GOOGLE_SEARCH_CONSOLE_DEFAULT_SYNC_DAYS ?? "28",
  GOOGLE_SEARCH_CONSOLE_MAX_SYNC_DAYS:
    process.env.GOOGLE_SEARCH_CONSOLE_MAX_SYNC_DAYS ?? "90",
  GOOGLE_SEARCH_CONSOLE_ROW_LIMIT:
    process.env.GOOGLE_SEARCH_CONSOLE_ROW_LIMIT ?? "25000",
  GOOGLE_SEARCH_CONSOLE_MAX_PAGES_PER_SYNC:
    process.env.GOOGLE_SEARCH_CONSOLE_MAX_PAGES_PER_SYNC ?? "10",
  GOOGLE_API_RETRY_ENABLED: process.env.GOOGLE_API_RETRY_ENABLED ?? "true",
  GOOGLE_API_MAX_RETRIES: process.env.GOOGLE_API_MAX_RETRIES ?? "2",
  GOOGLE_API_RETRY_BASE_DELAY_MS:
    process.env.GOOGLE_API_RETRY_BASE_DELAY_MS ?? "2000",
  GOOGLE_API_SYNC_LOCK_MINUTES:
    process.env.GOOGLE_API_SYNC_LOCK_MINUTES ?? "15",
  GOOGLE_API_LOG_PAYLOAD: process.env.GOOGLE_API_LOG_PAYLOAD ?? "false",
  GOOGLE_API_LOG_RESPONSE_SUMMARY:
    process.env.GOOGLE_API_LOG_RESPONSE_SUMMARY ?? "true",
  OPERATIONS_AUTOMATION_ENABLED:
    process.env.OPERATIONS_AUTOMATION_ENABLED ?? "false",
  OPERATIONS_DRY_RUN_MODE: process.env.OPERATIONS_DRY_RUN_MODE ?? "true",
  SCHEDULED_SYNC_ENABLED: process.env.SCHEDULED_SYNC_ENABLED ?? "false",
  SCHEDULED_SYNC_MOCK_MODE: process.env.SCHEDULED_SYNC_MOCK_MODE ?? "true",
  SYNC_WORKER_ENABLED: process.env.SYNC_WORKER_ENABLED ?? "true",
  SYNC_WORKER_INTERVAL_SECONDS:
    process.env.SYNC_WORKER_INTERVAL_SECONDS ?? "60",
  SYNC_MAX_JOBS_PER_TICK: process.env.SYNC_MAX_JOBS_PER_TICK ?? "3",
  SYNC_JOB_TIMEOUT_MINUTES: process.env.SYNC_JOB_TIMEOUT_MINUTES ?? "30",
  SYNC_STALE_LOCK_MINUTES: process.env.SYNC_STALE_LOCK_MINUTES ?? "30",
  SYNC_LEASE_HEARTBEAT_SECONDS:
    process.env.SYNC_LEASE_HEARTBEAT_SECONDS ?? "30",
  SYNC_MAX_RETRY_ATTEMPTS: process.env.SYNC_MAX_RETRY_ATTEMPTS ?? "2",
  SYNC_RETRY_BASE_DELAY_SECONDS:
    process.env.SYNC_RETRY_BASE_DELAY_SECONDS ?? "300",
  GA4_SCHEDULED_SYNC_ENABLED: process.env.GA4_SCHEDULED_SYNC_ENABLED ?? "false",
  GA4_SCHEDULED_SYNC_CRON: process.env.GA4_SCHEDULED_SYNC_CRON ?? "0 3 * * *",
  GA4_SCHEDULED_SYNC_DEFAULT_DAYS:
    process.env.GA4_SCHEDULED_SYNC_DEFAULT_DAYS ?? "7",
  GA4_MIN_QUOTA_REMAINING_TOKENS:
    process.env.GA4_MIN_QUOTA_REMAINING_TOKENS ?? "100",
  GSC_SCHEDULED_SYNC_ENABLED: process.env.GSC_SCHEDULED_SYNC_ENABLED ?? "false",
  GSC_SCHEDULED_SYNC_CRON: process.env.GSC_SCHEDULED_SYNC_CRON ?? "30 3 * * *",
  GSC_SCHEDULED_SYNC_DEFAULT_DAYS:
    process.env.GSC_SCHEDULED_SYNC_DEFAULT_DAYS ?? "7",
  GSC_QUERY_PAGE_SYNC_ENABLED:
    process.env.GSC_QUERY_PAGE_SYNC_ENABLED ?? "false",
  GROWTH_SCORE_AUTO_RECALC_ENABLED:
    process.env.GROWTH_SCORE_AUTO_RECALC_ENABLED ?? "false",
  GROWTH_SCORE_RECALC_CRON: process.env.GROWTH_SCORE_RECALC_CRON ?? "0 5 * * *",
  GSB_WEEKLY_REPORT_ENABLED: process.env.GSB_WEEKLY_REPORT_ENABLED ?? "false",
  GSB_WEEKLY_REPORT_CRON: process.env.GSB_WEEKLY_REPORT_CRON ?? "0 8 * * 1",
  ALERT_DETECTION_ENABLED: process.env.ALERT_DETECTION_ENABLED ?? "true",
  ALERT_DETECTION_MOCK_MODE: process.env.ALERT_DETECTION_MOCK_MODE ?? "true",
  ALERT_DETECTION_CRON: process.env.ALERT_DETECTION_CRON ?? "0 6 * * *",
  ALERT_DEDUP_WINDOW_HOURS: process.env.ALERT_DEDUP_WINDOW_HOURS ?? "24",
  ALERT_DEFAULT_COOLDOWN_HOURS:
    process.env.ALERT_DEFAULT_COOLDOWN_HOURS ?? "24",
  DATA_FRESHNESS_WARNING_HOURS:
    process.env.DATA_FRESHNESS_WARNING_HOURS ?? "48",
  DATA_FRESHNESS_CRITICAL_HOURS:
    process.env.DATA_FRESHNESS_CRITICAL_HOURS ?? "96",
  SEO_CLICKS_DROP_THRESHOLD_PERCENT:
    process.env.SEO_CLICKS_DROP_THRESHOLD_PERCENT ?? "30",
  SEO_IMPRESSIONS_DROP_THRESHOLD_PERCENT:
    process.env.SEO_IMPRESSIONS_DROP_THRESHOLD_PERCENT ?? "30",
  REVENUE_DROP_THRESHOLD_PERCENT:
    process.env.REVENUE_DROP_THRESHOLD_PERCENT ?? "40",
  SOCIAL_IMPRESSIONS_DROP_THRESHOLD_PERCENT:
    process.env.SOCIAL_IMPRESSIONS_DROP_THRESHOLD_PERCENT ?? "40",
  API_ERROR_SPIKE_THRESHOLD: process.env.API_ERROR_SPIKE_THRESHOLD ?? "5",
  NOTIFICATION_CENTER_ENABLED:
    process.env.NOTIFICATION_CENTER_ENABLED ?? "true",
  NOTIFICATION_MOCK_MODE: process.env.NOTIFICATION_MOCK_MODE ?? "true",
  EMAIL_NOTIFICATION_ENABLED: process.env.EMAIL_NOTIFICATION_ENABLED ?? "false",
  SLACK_NOTIFICATION_ENABLED: process.env.SLACK_NOTIFICATION_ENABLED ?? "false",
  ARTICLE_IMPROVEMENT_ENABLED:
    process.env.ARTICLE_IMPROVEMENT_ENABLED ?? "true",
  ARTICLE_IMPROVEMENT_MOCK_MODE:
    process.env.ARTICLE_IMPROVEMENT_MOCK_MODE ?? "true",
  REWRITE_DRAFT_ENABLED: process.env.REWRITE_DRAFT_ENABLED ?? "true",
  REWRITE_DRAFT_MOCK_MODE: process.env.REWRITE_DRAFT_MOCK_MODE ?? "true",
  REWRITE_REQUIRE_HUMAN_APPROVAL:
    process.env.REWRITE_REQUIRE_HUMAN_APPROVAL ?? "true",
  REWRITE_REQUIRE_REAPPROVAL_ON_CHANGE:
    process.env.REWRITE_REQUIRE_REAPPROVAL_ON_CHANGE ?? "true",
  WORDPRESS_REWRITE_DRAFT_UPDATE_ENABLED:
    process.env.WORDPRESS_REWRITE_DRAFT_UPDATE_ENABLED ?? "false",
  WORDPRESS_PUBLISHED_POST_DIRECT_UPDATE_ENABLED:
    process.env.WORDPRESS_PUBLISHED_POST_DIRECT_UPDATE_ENABLED ?? "false",
  WORDPRESS_REWRITE_CREATE_NEW_DRAFT_ENABLED:
    process.env.WORDPRESS_REWRITE_CREATE_NEW_DRAFT_ENABLED ?? "true",
  WORDPRESS_REWRITE_UPDATE_EXISTING_DRAFT_ENABLED:
    process.env.WORDPRESS_REWRITE_UPDATE_EXISTING_DRAFT_ENABLED ?? "true",
  WORDPRESS_REWRITE_DEFAULT_MODE:
    process.env.WORDPRESS_REWRITE_DEFAULT_MODE ?? "create_new_draft",
  WORDPRESS_REWRITE_REQUEST_TIMEOUT_MS:
    process.env.WORDPRESS_REWRITE_REQUEST_TIMEOUT_MS ?? "20000",
  WORDPRESS_REWRITE_REQUIRE_MODIFIED_CHECK:
    process.env.WORDPRESS_REWRITE_REQUIRE_MODIFIED_CHECK ?? "true",
  CONTENT_DIFF_ENABLED: process.env.CONTENT_DIFF_ENABLED ?? "true",
  CONTENT_DIFF_MAX_CONTENT_LENGTH:
    process.env.CONTENT_DIFF_MAX_CONTENT_LENGTH ?? "120000",
  CONTENT_SNAPSHOT_ENABLED: process.env.CONTENT_SNAPSHOT_ENABLED ?? "true",
  CONTENT_SANITIZE_HTML_ENABLED:
    process.env.CONTENT_SANITIZE_HTML_ENABLED ?? "true",
  CONTENT_BLOCK_STRUCTURE_WARNING_ENABLED:
    process.env.CONTENT_BLOCK_STRUCTURE_WARNING_ENABLED ?? "true",
  SEO_IMPACT_MEASUREMENT_ENABLED:
    process.env.SEO_IMPACT_MEASUREMENT_ENABLED ?? "true",
  SEO_IMPACT_DEFAULT_DAYS_BEFORE:
    process.env.SEO_IMPACT_DEFAULT_DAYS_BEFORE ?? "28",
  SEO_IMPACT_DEFAULT_DAYS_AFTER:
    process.env.SEO_IMPACT_DEFAULT_DAYS_AFTER ?? "28",
  SEO_IMPACT_MIN_DAYS_AFTER: process.env.SEO_IMPACT_MIN_DAYS_AFTER ?? "7",
  SEO_IMPACT_MIN_CLICKS: process.env.SEO_IMPACT_MIN_CLICKS ?? "20",
  SEO_IMPACT_MIN_IMPRESSIONS: process.env.SEO_IMPACT_MIN_IMPRESSIONS ?? "500",
  IMPROVEMENT_TASK_AUTO_CREATE_ENABLED:
    process.env.IMPROVEMENT_TASK_AUTO_CREATE_ENABLED ?? "false",
  IMPROVEMENT_TASK_REQUIRE_APPROVAL:
    process.env.IMPROVEMENT_TASK_REQUIRE_APPROVAL ?? "true",
  REWRITE_RISK_CHECK_ENABLED: process.env.REWRITE_RISK_CHECK_ENABLED ?? "true",
  REWRITE_HIGH_RISK_KEYWORDS_ENABLED:
    process.env.REWRITE_HIGH_RISK_KEYWORDS_ENABLED ?? "true",
  REWRITE_CRITICAL_RISK_BLOCKS_WORDPRESS_UPDATE:
    process.env.REWRITE_CRITICAL_RISK_BLOCKS_WORDPRESS_UPDATE ?? "true",
  SNS_REAL_POSTING_ENABLED: process.env.SNS_REAL_POSTING_ENABLED ?? "false",
  SNS_POSTING_MOCK_MODE: process.env.SNS_POSTING_MOCK_MODE ?? "true",
  SNS_REQUIRE_HUMAN_APPROVAL: process.env.SNS_REQUIRE_HUMAN_APPROVAL ?? "true",
  SNS_REQUIRE_LINK_CHECK: process.env.SNS_REQUIRE_LINK_CHECK ?? "true",
  SNS_REQUIRE_RISK_CHECK: process.env.SNS_REQUIRE_RISK_CHECK ?? "true",
  SNS_PREVENT_DIRECT_AFFILIATE_LINK:
    process.env.SNS_PREVENT_DIRECT_AFFILIATE_LINK ?? "true",
  SNS_MANUAL_REVIEW_ON_UNKNOWN_STATUS:
    process.env.SNS_MANUAL_REVIEW_ON_UNKNOWN_STATUS ?? "true",
  SNS_POST_WORKER_ENABLED: process.env.SNS_POST_WORKER_ENABLED ?? "false",
  SNS_POST_WORKER_INTERVAL_SECONDS:
    process.env.SNS_POST_WORKER_INTERVAL_SECONDS ?? "60",
  SNS_POST_WORKER_MAX_PER_TICK: process.env.SNS_POST_WORKER_MAX_PER_TICK ?? "3",
  SNS_DEDUP_WINDOW_DAYS: process.env.SNS_DEDUP_WINDOW_DAYS ?? "14",
  SNS_RETRY_MAX_ATTEMPTS: process.env.SNS_RETRY_MAX_ATTEMPTS ?? "2",
  SNS_RETRY_BASE_DELAY_SECONDS:
    process.env.SNS_RETRY_BASE_DELAY_SECONDS ?? "300",
  SNS_PERFORMANCE_SYNC_ENABLED:
    process.env.SNS_PERFORMANCE_SYNC_ENABLED ?? "false",
  SNS_GROWTH_SCORE_ENABLED: process.env.SNS_GROWTH_SCORE_ENABLED ?? "true",
  X_API_ENABLED: process.env.X_API_ENABLED ?? "false",
  X_POSTING_ENABLED: process.env.X_POSTING_ENABLED ?? "false",
  X_MOCK_MODE: process.env.X_MOCK_MODE ?? "true",
  X_OAUTH_CLIENT_ID: process.env.X_OAUTH_CLIENT_ID ?? "",
  X_OAUTH_CLIENT_SECRET: process.env.X_OAUTH_CLIENT_SECRET ?? "",
  X_OAUTH_REDIRECT_URI:
    process.env.X_OAUTH_REDIRECT_URI ??
    "http://127.0.0.1:3000/api/x/oauth/callback",
  X_TOKEN_ENCRYPTION_KEY: process.env.X_TOKEN_ENCRYPTION_KEY ?? "",
  X_OAUTH_SCOPES:
    process.env.X_OAUTH_SCOPES ??
    "tweet.read tweet.write users.read offline.access media.write",
  X_MEDIA_SIMPLE_UPLOAD_ENABLED:
    process.env.X_MEDIA_SIMPLE_UPLOAD_ENABLED ?? "true",
  X_MEDIA_CHUNKED_UPLOAD_ENABLED:
    process.env.X_MEDIA_CHUNKED_UPLOAD_ENABLED ?? "false",
  X_MEDIA_ALLOWED_IMAGE_TYPES:
    process.env.X_MEDIA_ALLOWED_IMAGE_TYPES ??
    "image/jpeg,image/png,image/gif,image/webp",
  X_POST_DEFAULT_MADE_WITH_AI:
    process.env.X_POST_DEFAULT_MADE_WITH_AI ?? "false",
  X_POST_PAID_PARTNERSHIP_ENABLED:
    process.env.X_POST_PAID_PARTNERSHIP_ENABLED ?? "false",
  X_RATE_LIMIT_STOP_ON_429: process.env.X_RATE_LIMIT_STOP_ON_429 ?? "true",
  CAMPAIGN_MANAGEMENT_ENABLED:
    process.env.CAMPAIGN_MANAGEMENT_ENABLED ?? "true",
  CAMPAIGN_MANAGEMENT_MOCK_MODE:
    process.env.CAMPAIGN_MANAGEMENT_MOCK_MODE ?? "true",
  CONTENT_CALENDAR_ADVANCED_ENABLED:
    process.env.CONTENT_CALENDAR_ADVANCED_ENABLED ?? "true",
  CONTENT_CALENDAR_MOCK_MODE: process.env.CONTENT_CALENDAR_MOCK_MODE ?? "true",
  CONTENT_CALENDAR_CONFLICT_DETECTION_ENABLED:
    process.env.CONTENT_CALENDAR_CONFLICT_DETECTION_ENABLED ?? "true",
  CONTENT_CALENDAR_MAX_SOCIAL_POSTS_PER_DAY:
    process.env.CONTENT_CALENDAR_MAX_SOCIAL_POSTS_PER_DAY ?? "3",
  CONTENT_CALENDAR_MAX_CAMPAIGNS_OVERLAP:
    process.env.CONTENT_CALENDAR_MAX_CAMPAIGNS_OVERLAP ?? "3",
  CAMPAIGN_ROI_ENABLED: process.env.CAMPAIGN_ROI_ENABLED ?? "true",
  CAMPAIGN_ROI_DEFAULT_PERIOD_DAYS:
    process.env.CAMPAIGN_ROI_DEFAULT_PERIOD_DAYS ?? "28",
  CAMPAIGN_ROI_MIN_DATA_DAYS: process.env.CAMPAIGN_ROI_MIN_DATA_DAYS ?? "7",
  CAMPAIGN_ROI_DEFAULT_CURRENCY:
    process.env.CAMPAIGN_ROI_DEFAULT_CURRENCY ?? "JPY",
  CAMPAIGN_ROI_REQUIRE_APPROVED_REVENUE_VIEW:
    process.env.CAMPAIGN_ROI_REQUIRE_APPROVED_REVENUE_VIEW ?? "true",
  CAMPAIGN_ROI_ALLOW_PENDING_VIEW:
    process.env.CAMPAIGN_ROI_ALLOW_PENDING_VIEW ?? "true",
  CAMPAIGN_ROI_PREVENT_DOUBLE_COUNT:
    process.env.CAMPAIGN_ROI_PREVENT_DOUBLE_COUNT ?? "true",
  CAMPAIGN_ATTRIBUTION_ENABLED:
    process.env.CAMPAIGN_ATTRIBUTION_ENABLED ?? "true",
  CAMPAIGN_ATTRIBUTION_DEFAULT_METHOD:
    process.env.CAMPAIGN_ATTRIBUTION_DEFAULT_METHOD ?? "direct",
  CAMPAIGN_ATTRIBUTION_ALLOW_ALLOCATION_RATE:
    process.env.CAMPAIGN_ATTRIBUTION_ALLOW_ALLOCATION_RATE ?? "true",
  CAMPAIGN_GROWTH_SCORE_ENABLED:
    process.env.CAMPAIGN_GROWTH_SCORE_ENABLED ?? "true",
  CAMPAIGN_RECOMMENDATION_ENABLED:
    process.env.CAMPAIGN_RECOMMENDATION_ENABLED ?? "true",
  CAMPAIGN_REQUIRE_HUMAN_REVIEW:
    process.env.CAMPAIGN_REQUIRE_HUMAN_REVIEW ?? "true",
  REPORT_GENERATION_ENABLED: process.env.REPORT_GENERATION_ENABLED ?? "true",
  REPORT_GENERATION_MOCK_MODE:
    process.env.REPORT_GENERATION_MOCK_MODE ?? "true",
  REPORT_AUTO_GENERATION_ENABLED:
    process.env.REPORT_AUTO_GENERATION_ENABLED ?? "false",
  REPORT_DEFAULT_PERIOD: process.env.REPORT_DEFAULT_PERIOD ?? "weekly",
  REPORT_REQUIRE_HUMAN_REVIEW:
    process.env.REPORT_REQUIRE_HUMAN_REVIEW ?? "true",
  REPORT_IDEMPOTENCY_ENABLED: process.env.REPORT_IDEMPOTENCY_ENABLED ?? "true",
  REPORT_EXPORT_ENABLED: process.env.REPORT_EXPORT_ENABLED ?? "true",
  REPORT_EXPORT_MOCK_MODE: process.env.REPORT_EXPORT_MOCK_MODE ?? "true",
  REPORT_EXPORT_FORMATS:
    process.env.REPORT_EXPORT_FORMATS ?? "markdown,csv,json",
  REPORT_EXTERNAL_SEND_ENABLED:
    process.env.REPORT_EXTERNAL_SEND_ENABLED ?? "false",
  CAMPAIGN_ALERTS_ENABLED: process.env.CAMPAIGN_ALERTS_ENABLED ?? "true",
  CAMPAIGN_RISK_CHECK_ENABLED:
    process.env.CAMPAIGN_RISK_CHECK_ENABLED ?? "true",
  CAMPAIGN_COST_TRACKING_ENABLED:
    process.env.CAMPAIGN_COST_TRACKING_ENABLED ?? "true",
  CAMPAIGN_WORKLOAD_TRACKING_ENABLED:
    process.env.CAMPAIGN_WORKLOAD_TRACKING_ENABLED ?? "true",
  BUSINESS_INSIGHT_ENABLED: process.env.BUSINESS_INSIGHT_ENABLED ?? "true",
  BUSINESS_INSIGHT_REQUIRE_HUMAN_REVIEW:
    process.env.BUSINESS_INSIGHT_REQUIRE_HUMAN_REVIEW ?? "true",
};

export type SettingKey = keyof typeof DEFAULT_SETTINGS;

export async function getSetting(key: SettingKey) {
  const setting = await prisma.setting.findUnique({ where: { key } });
  return setting?.value ?? DEFAULT_SETTINGS[key];
}

export async function getSettings() {
  const rows = await prisma.setting.findMany();
  const values = new Map(rows.map((row) => [row.key, row.value]));
  return Object.fromEntries(
    Object.entries(DEFAULT_SETTINGS).map(([key, fallback]) => [
      key,
      values.get(key) ?? fallback,
    ]),
  ) as Record<SettingKey, string>;
}

export function parseCsv(value: string) {
  return value
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

export function parseBoolean(value: string) {
  return value.toLowerCase() === "true";
}
